---
# Account configuration
accountConfigurationList:
  - accountName: MaximePRZ # Name of your account
    accountLogin: max.perez1313@gmail.com # Login of your account
    accountPassword: buijYXAql6n3uDh2R8f0 # Password of your account

# If enabled, seed list will be ignored and every match will be played against a random seed
randomSeed: false

# The name of the multiplayer game as it appears at the end of the url of your IDE
multiName: code-royale

# Optional. Indicates if the game is a contest or not. FALSE if not provided
isContest: false

# List of seeds to play
seedList:
  - seed=747848718
  - seed=851888179
  - seed=700073541
  - seed=683972927
  - seed=586660547
  - seed=410110611

# Cooldown between every match, 20 is the minimum to avoid CG's limitation
requestCooldown: 20

# [0, N] forced start position at N
# -1 : Each seed is played with every starting positions configuration. (Works only with fixed seed list).
#       In 1v1, it will generate 2 games, 6 games in 1v2 and 24 games in 1v3. Best suited for non symmetrical and/or turn-based games.
# -2 : Each seed is played once, with random starting positions. Best suited for perfectly symmetrical 
#       and non turn-based games in which starting position doesn't really matter, like MM, GoD, CotC, GitC, ...
playerPosition: -2

# Minimum number of enemies to play against
minEnemiesNumber: 1

# Maximum number of enemies to play against
maxEnemiesNumber: 1

# List of tested codes
codeConfigurationList:
  - sourcePath: ..\target\Player.java
    nbReplays: 1 # Number of times each seed will be played
    language: Java # Code language
    enemies: # Enemies list. At each game, random enemies are picked from this list (their number is also picked randomly between <minEnemiesNumber> and <maxEnemiesNumber>)
      - agentId: '2592115' # Enemy agentId
        name: yannOrhon # Enemy name
      - agentId: '2217825'
        name: Shadaia
      - agentId: '2750906'
        name: MaximePRZ
  - sourcePath: .\myBots\Player64809570.java
# -- The following values are the default ones that are used if not defined in the codeConfigurationList

# Default value for nbReplays
defaultNbReplays: 6

# Default value for language
defaultLanguage: java

# Default value for enemies
defaultEnemies:
  - agentId: '123456'
    name: Recar
  - agentId: '344556'
    name: Illedan